### ISSUE TITLE
menu-image is dependant on HiveMind

### ISSUE THREAD

**Issue by samhamilton** [moqui/SimpleScreens#1]
Hey David, 

I am sure you know but the menu-image in Accounting.xml, User.xml and Vendor.xml points to /hmstatic/images/ which might not always be included and so could cause problems. 

Thanks
Sam

**Comment by jonesde** [comment]
Yes, thanks for the reminder. I noticed those when moving the files over but haven't decided on whether to move the static files over or just removing references to them in SimpleScreens and having them only in HiveMind and PopCommerce. I'll get this resolved soon.

**Comment by jonesde** [comment]
This is fixed in commit #e2078ef
