### ISSUE TITLE
Recommendation: include lang-all.js (FullCalendar's languages pack) into SimpleScreens ssstatic/lib

### ISSUE THREAD

**Issue by mrovnanik** [moqui/SimpleScreens#11]
I suppose it would be fine to have localization support for FullCalendar. My customers need slovak language, so I imlemented it.

https://github.com/moqui/SimpleScreens/tree/master/screen/ssstatic/lib/fullcalendar

Download location: http://fullcalendar.io/download
Localization implementation: http://fullcalendar.io/docs/text/lang/

**Comment by jonesde** [comment]
Any chance you could share what you did, maybe even submit a pull request? To do a pull request you should make a fork of the repository (in this case moqui/SimpleScreens), and put in it only the changes you would like to submit, then create a pull request for the repository.

**Comment by jonesde** [comment]
Thank you for the pull request, now merged.
