### ISSUE TITLE
Find button does not work on AssetOnHandSummary

### ISSUE THREAD

**Issue by zhangwei1979** [moqui/SimpleScreens#120]
To reproduct it

1. Goto https://demo.moqui.org/qapps/PopcAdmin/Accounting/Reports/AssetOnHandSummary
2. Click FindOptions
3. Select a Facility
4. Click Find

It is caused by Field Descriptions popup. It can fixed by removing Field Descriptions popup or changing  FieldDescriptions form skip-form to false

**Comment by jonesde** [comment]
This was an issue with the qvt screen macros in form-list, see moqui-runtime commit b5ec312 for the fix.
