### ISSUE TITLE
Error: Could not find subscreen or transition or file/content [invoiceOrderPart]

### ISSUE THREAD

**Issue by locnguyenx** [moqui/SimpleScreens#13]
Completed error message:
` [Error: Could not find subscreen or transition or file/content [invoiceOrderPart] under screen [component://SimpleScreens/screen/SimpleScreens/Order/OrderDetail.xml] while finding url for path [apps, PopcAdmin, Order, OrderDetail, invoiceOrderPart] under from screen [component://SimpleScreens/screen/SimpleScreens/Order/OrderDetail.xml]]`

**Comment by jonesde** [comment]
Thank you, missing transition (invoiceOrderPart) added in commit #c77b3e4.
