### ISSUE TITLE
missing transition "editFeature" in screen EditAssocs.xml

### ISSUE THREAD

**Issue by locnguyenx** [moqui/SimpleScreens#5]
problematic screen: //SimpleScreens/Catalog/Product/EditAssocs.xml
error in form "AllSelectableFeaturesForm" due to missing transition "editFeature"
I try to add new transition and it works well:
<transition name="editFeature"><default-response url="../../Feature/EditFeature"/></transition>

**Comment by jonesde** [comment]
Thank you, this is fixed in commit #f60e093.
