### ISSUE TITLE
Missing FindOptionsForm in FindCustomer and FindSupplier screen

### ISSUE THREAD

**Issue by locnguyenx** [moqui/SimpleScreens#60]
In recent commits, FindOptionsForm has been removed in `screen/SimpleScreens/Party/FindParty.xml`, but it's still used in screens `SimpleScreens/Customer/FindCustomer.xml` and `SimpleScreens/Supplier/FindSupplier.xml`.

These screens should be fixed in accordingly.

**Comment by jonesde** [comment]
This was a work in progress, and is now complete.
