### ISSUE TITLE
require.js can not match the redefined define() function 

### ISSUE THREAD

**Issue by gagaboy** [moqui/SimpleScreens#66]
When I just simply include require.js in the Header.html.ftl and do nothing ,there are some js errors in the browser console.And I found that in the MyAccountNav.js and ActiveOrgNav.js code,there is a define() which is redefined in the WebrootVue.js. 
If I use  require.js ,the definition of define() comes from require, and the implementation of moqui.loadComponent is not well match the require.js.
I change the window.define to moqui.define ,it seems work well.

**Comment by jonesde** [comment]
Simply adding require.js will break all sorts of things. If you use require you have to change how nearly all JS libraries are loaded, including various workarounds for jQuery. You can't just drop it in with a bunch of other JS libraries and expect all to work, the require.js docs are very clear about that.
